### ISSUE TITLE
Error in xw_json.ml: Unbound type constructor value

### ISSUE THREAD

**Issue by slegrand45** [martindemello/crosspad#1]
With OCaml 4.03.0 and up to date OPAM dependencies, trying to build the code i get:

`File "src/converter/xw_json.ml", line 20, characters 12-17:`
`Error: Unbound type constructor value`

**Comment by martindemello** [comment]
I switched to 4.03 and did a fresh git checkout and it built fine for me. `value` is from `Ezjsonm.value` - could you check that you have `ezjsonm 0.4.3` installed?

(also, how did you build it? i switched to oasis very recently and might have messed something up so that it only works on my system. for me just doing a git checkout and running `make` builds everything )

**Comment by slegrand45** [comment]
Indeed, i had `ezjsonm 0.2.0`. Don't know why because i did an `opam update` and `opam upgrade` before trying to install `crosspad`. Anyway, with `ezjsonm 0.4.3` it now works with the command `opam pin add crosspad git://github.com/martindemello/crosspad.git`. Thanks!
